### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by rebelinux** [Darkemon/ZenPacks.Darkemon.ZenCustomMap#3]
1. Is there any way to configure the maps to only show events based on ping down only?
2. Is there any possibility to implement a user permission check for map deletions so we can prevent the deletion of maps from unauthorized users?

**Comment by Darkemon** [comment]
Hi! 

1 and 2: this is possible, but needs to upgrade server and client side (Flash part).

**Comment by bobmA** [comment]
I agree it would be good if there were permissions for editing the maps.
I'm not a Flash programmer, so I can only make changes to the server side.  I think it should be possible to get the user permissions, however without modifying the Flash to check the permissions the best that could be done would be to prevent the changes being saved to file, and when refreshed it would revert to how it was.  This would probably be very confusing for the users and cause a lot of bug reports.  If somebody is willing to do the Flash part, then I'll look at the server side.
